### ISSUE TITLE
Submit the api to packagist

### ISSUE THREAD

**Issue by dowadidi** [stefandoorn/becosoft-fashionpro-nl-php-api#1]
Hi Stefan.

I've noticed you already have some packages present at packagist. Could you add this one to?
And maybe some basic documentation. That would be helpful.

Thank you in advance!

**Comment by stefandoorn** [comment]
Hi @DiederikVanHoorebeke, sure, that's the plan :) I only recently started working on a project where I needed something like this, so it's heavily under development and far from stable yet, therefor I didn't submit it yet and also no documentation yet.

If it helps your project, I'll submit it to Packagist asap. I would be happy to receive PR's on the project to extend functionality.

**Comment by stefandoorn** [comment]
Another thing that I'm not yet sure of is whether the API is generic for all their branches. I'm currently using it for a fashion implementation, but they also have non-food, food & web. The endpoint included the branch at the moment: 'fashionpro'. If an API is branch specific, I prefer to adjust the name of this library or split it in a base library & a branch specific library. If you have info on this, let me know.

**Comment by dowadidi** [comment]
Well, I use it for the fashionpro API too. I don't have any info on the other APIs. But I'm sure the APIs are different for each branch. I suppose "Wasvoorschrift" isn't something you need for food. :-)

**Comment by stefandoorn** [comment]
Haha indeed :) Alright, then I probably rename it to prevent confusion and then add it to Packagist. Keep you posted :)

**Comment by stefandoorn** [comment]
@DiederikVanHoorebeke Here you go: https://packagist.org/packages/stefandoorn/becosoft-fashionpro-nl-php-api.

It seems an English version of the API is on it's way, and I got confirmed that other branches do not have API's, so it's mainly the fashion API being used.

In my current project I've only used fetching articles up to now, but will have to implement orders and customers etc. later on. Please free to submit PR's to add functionality to the library ofcourse.

Things are still in heavy development, but I hope the README is clear to get started with it.
